/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
/**
 *
 * @author NICOLAS
 */
public class Gui_MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalGUI
     */
    public Gui_MenuPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTratamientos = new javax.swing.JButton();
        btnControlVacunas = new javax.swing.JButton();
        btnHistoriasClinicas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnMascotas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Jmenu_Config = new javax.swing.JMenu();
        Item_cerrar_sesion = new javax.swing.JMenuItem();
        Item_salir = new javax.swing.JMenuItem();
        menuGestionUsuario = new javax.swing.JMenu();
        Item_Conexion = new javax.swing.JMenuItem();
        Item_GestionUsuario = new javax.swing.JMenuItem();
        Item_GestionPermisos = new javax.swing.JMenuItem();
        Item_Permisos = new javax.swing.JMenuItem();
        GestionPersonal = new javax.swing.JMenu();
        Item_Listadopersonal = new javax.swing.JMenuItem();
        Item_AgregarPersonal = new javax.swing.JMenuItem();
        menuServicios = new javax.swing.JMenu();
        Item_ListarServicios = new javax.swing.JMenuItem();
        Item_AgregarServicio = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        item_list_gestConsul = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JMenu();
        menuPagos = new javax.swing.JMenu();
        menuAbastecimiento = new javax.swing.JMenu();
        item_reg_prod = new javax.swing.JMenuItem();
        item_list_prod = new javax.swing.JMenuItem();
        item_reg_proveedor = new javax.swing.JMenuItem();
        item_list_proveedor = new javax.swing.JMenuItem();
        item_reg_compra = new javax.swing.JMenuItem();
        item_list_compra_aprob = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        item_reporte_orden_compra = new javax.swing.JMenuItem();
        item_reporte_orden_repo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Item_ListarTratamiento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System Veterinaria");
        setBackground(new java.awt.Color(255, 51, 51));
        setMinimumSize(new java.awt.Dimension(886, 523));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        btnTratamientos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnTratamientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img_Tratamiento.png"))); // NOI18N
        btnTratamientos.setText("Tratamientos");
        btnTratamientos.setFocusPainted(false);
        getContentPane().add(btnTratamientos);

        btnControlVacunas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnControlVacunas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img_Vacunas.png"))); // NOI18N
        btnControlVacunas.setText("Control de Vacunas");
        btnControlVacunas.setFocusPainted(false);
        getContentPane().add(btnControlVacunas);

        btnHistoriasClinicas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnHistoriasClinicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img_HistoriasClinicas.png"))); // NOI18N
        btnHistoriasClinicas.setText("Historias Clinicas");
        btnHistoriasClinicas.setFocusPainted(false);
        getContentPane().add(btnHistoriasClinicas);

        btnClientes.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img_Clientes.png"))); // NOI18N
        btnClientes.setText("Cliente");
        btnClientes.setFocusPainted(false);
        getContentPane().add(btnClientes);

        btnMascotas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnMascotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img_Mascota.png"))); // NOI18N
        btnMascotas.setText("Mascotas");
        btnMascotas.setFocusPainted(false);
        getContentPane().add(btnMascotas);

        jMenuBar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        Jmenu_Config.setText("Archivo");
        Jmenu_Config.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        Item_cerrar_sesion.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Item_cerrar_sesion.setText("Cerrar Sesion");
        Jmenu_Config.add(Item_cerrar_sesion);

        Item_salir.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Item_salir.setText("Salir");
        Jmenu_Config.add(Item_salir);

        jMenuBar1.add(Jmenu_Config);

        menuGestionUsuario.setText("Administración");
        menuGestionUsuario.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        menuGestionUsuario.setHideActionText(true);
        menuGestionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionUsuarioActionPerformed(evt);
            }
        });

        Item_Conexion.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Item_Conexion.setText("Conexion a servidor");
        menuGestionUsuario.add(Item_Conexion);

        Item_GestionUsuario.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Item_GestionUsuario.setText("Gestionar Usuarios");
        menuGestionUsuario.add(Item_GestionUsuario);

        Item_GestionPermisos.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Item_GestionPermisos.setText("Control de Permisos");
        menuGestionUsuario.add(Item_GestionPermisos);

        Item_Permisos.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Item_Permisos.setText("Registrar Permisos");
        menuGestionUsuario.add(Item_Permisos);

        jMenuBar1.add(menuGestionUsuario);

        GestionPersonal.setText("Gestion de Personal");
        GestionPersonal.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        Item_Listadopersonal.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Item_Listadopersonal.setText("Listado del Personal");
        GestionPersonal.add(Item_Listadopersonal);

        Item_AgregarPersonal.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Item_AgregarPersonal.setText("Registrar Personal");
        Item_AgregarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_AgregarPersonalActionPerformed(evt);
            }
        });
        GestionPersonal.add(Item_AgregarPersonal);

        jMenuBar1.add(GestionPersonal);

        menuServicios.setText("Servicios");
        menuServicios.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        Item_ListarServicios.setText("Listar Servicios");
        menuServicios.add(Item_ListarServicios);

        Item_AgregarServicio.setText("Agregar Servicio");
        menuServicios.add(Item_AgregarServicio);

        jMenuBar1.add(menuServicios);

        menuConsultas.setText("Consultas");
        menuConsultas.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        item_list_gestConsul.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        item_list_gestConsul.setText("Gestión de Consultas");
        menuConsultas.add(item_list_gestConsul);

        jMenuBar1.add(menuConsultas);

        menuVentas.setText("Ventas");
        menuVentas.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jMenuBar1.add(menuVentas);

        menuPagos.setText("Pagos");
        menuPagos.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jMenuBar1.add(menuPagos);

        menuAbastecimiento.setText("Compras");
        menuAbastecimiento.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        item_reg_prod.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        item_reg_prod.setText("Registro de productos");
        menuAbastecimiento.add(item_reg_prod);

        item_list_prod.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        item_list_prod.setText("Lista de productos");
        menuAbastecimiento.add(item_list_prod);

        item_reg_proveedor.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        item_reg_proveedor.setText("Registro de proveedor");
        menuAbastecimiento.add(item_reg_proveedor);

        item_list_proveedor.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        item_list_proveedor.setText("Lista de proveedores");
        menuAbastecimiento.add(item_list_proveedor);

        item_reg_compra.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        item_reg_compra.setText("Registro de compra");
        menuAbastecimiento.add(item_reg_compra);

        item_list_compra_aprob.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        item_list_compra_aprob.setText("Lista de compras ");
        item_list_compra_aprob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_list_compra_aprobActionPerformed(evt);
            }
        });
        menuAbastecimiento.add(item_list_compra_aprob);

        jMenuBar1.add(menuAbastecimiento);

        menuReportes.setText("Reportes");
        menuReportes.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        item_reporte_orden_compra.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        item_reporte_orden_compra.setText("Orden de compra");
        menuReportes.add(item_reporte_orden_compra);

        item_reporte_orden_repo.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        item_reporte_orden_repo.setText("Orden de reposicion");
        menuReportes.add(item_reporte_orden_repo);

        jMenuBar1.add(menuReportes);

        jMenu1.setText("Tratamiento");

        Item_ListarTratamiento.setText("Listar Tratamientos");
        jMenu1.add(Item_ListarTratamiento);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuGestionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuGestionUsuarioActionPerformed

    private void Item_AgregarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_AgregarPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Item_AgregarPersonalActionPerformed

    private void item_list_compra_aprobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_list_compra_aprobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_list_compra_aprobActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu GestionPersonal;
    public javax.swing.JMenuItem Item_AgregarPersonal;
    public javax.swing.JMenuItem Item_AgregarServicio;
    public javax.swing.JMenuItem Item_Conexion;
    public javax.swing.JMenuItem Item_GestionPermisos;
    public javax.swing.JMenuItem Item_GestionUsuario;
    public javax.swing.JMenuItem Item_Listadopersonal;
    public javax.swing.JMenuItem Item_ListarServicios;
    public javax.swing.JMenuItem Item_ListarTratamiento;
    public javax.swing.JMenuItem Item_Permisos;
    public javax.swing.JMenuItem Item_cerrar_sesion;
    public javax.swing.JMenuItem Item_salir;
    public javax.swing.JMenu Jmenu_Config;
    public javax.swing.JButton btnClientes;
    public javax.swing.JButton btnControlVacunas;
    public javax.swing.JButton btnHistoriasClinicas;
    public javax.swing.JButton btnMascotas;
    public javax.swing.JButton btnTratamientos;
    public javax.swing.JMenuItem item_list_compra_aprob;
    public javax.swing.JMenuItem item_list_gestConsul;
    public javax.swing.JMenuItem item_list_prod;
    public javax.swing.JMenuItem item_list_proveedor;
    public javax.swing.JMenuItem item_reg_compra;
    public javax.swing.JMenuItem item_reg_prod;
    public javax.swing.JMenuItem item_reg_proveedor;
    public javax.swing.JMenuItem item_reporte_orden_compra;
    public javax.swing.JMenuItem item_reporte_orden_repo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu menuAbastecimiento;
    public javax.swing.JMenu menuConsultas;
    public javax.swing.JMenu menuGestionUsuario;
    public javax.swing.JMenu menuPagos;
    public javax.swing.JMenu menuReportes;
    public javax.swing.JMenu menuServicios;
    public javax.swing.JMenu menuVentas;
    // End of variables declaration//GEN-END:variables
}
